local Config = require("pf.config")
local Session = require("pf.session")
local Input = require("pf.input")
local Effects = require("pf.effects")
local Trajectory = require("pf.trajectory")
local total, failures = 0, {}
local function equal(actual, expected)
    assert(actual == expected, tostring(actual) .. " ~= " .. tostring(expected))
end
local function near(actual, expected)
    assert(math.abs(actual - expected) < 0.00001, tostring(actual) .. " ~= " .. tostring(expected))
end
local function test(name, run)
    total = total + 1
    local ok, err = pcall(run)
    if not ok then failures[#failures + 1] = name .. ": " .. tostring(err) end
end
local function ready()
    local session = Session.new(Config.validate({}))
    assert(session:handshake("1.0.0", 1))
    return session
end
local aim = { X = 1, Y = 0, Z = 0 }
local function player(value) return { eligible = true, current = value or 0, maximum = 100 } end

test("eight seconds fully relieves existing need", function()
    local s, p = ready(), player()
    for i = 1, 80 do
        s:input(i, true, aim, i / 10)
        p.current = assert(s:tick(i / 10, 0.1, p))
    end
    near(p.current, 100); equal(s.active, false); equal(s.latched, true)
end)
test("partial release preserves partial relief", function()
    local s, p = ready(), player(40)
    s:input(1, true, aim, 0)
    near(s:tick(0, 0.1, p), 41.25)
    s:input(2, false, nil, 0.1)
    equal(s:tick(0.1, 0.1, p), nil); equal(s.active, false)
end)
test("full bladder relief requires a fresh release before restarting", function()
    local s = ready()
    s:input(1, true, aim, 0)
    near(s:tick(0, 0.1, player(99)), 100)
    s:input(2, true, aim, 0.1)
    equal(s:tick(0.1, 0.1, player(98)), nil)
    s:input(3, false, nil, 0.2)
    s:input(4, true, aim, 0.3)
    near(s:tick(0.3, 0.1, player(98)), 99.25)
end)
test("holding while empty cannot restart on natural need decay", function()
    local s = ready(); s:input(1, true, aim, 0)
    equal(s:tick(0, 0.1, player(100)), nil)
    equal(s:tick(0.1, 0.1, player(99)), nil)
end)
test("timeout stops at exactly one second", function()
    local s = ready(); s:input(1, true, aim, 0)
    assert(s:tick(0.1, 0.1, player()))
    equal(s:tick(1, 0.1, player()), nil); equal(s.reason, "input_timeout")
    s:input(2, true, aim, 1.1)
    equal(s:tick(1.1, 0.1, player()), nil)
end)
test("stalled frames cannot create bonus relief", function()
    local s = ready(); s:input(1, true, aim, 5)
    near(s:tick(5, 30, player()), 1.25)
end)
test("unready and incompatible sessions cannot modify stats", function()
    local s = Session.new(Config.validate({}))
    equal(s:input(1, true, aim, 0), false)
    equal(s:handshake("2.0.0", 1), false)
    equal(s:handshake("1.0.0", 2), false)
    equal(s:tick(0, 0.1, player()), nil)
end)
test("stale start packets cannot undo a release", function()
    local s = ready(); s:input(10, true, aim, 0); s:input(12, false, nil, 0.1)
    equal(s:input(11, true, aim, 0.2), false)
    equal(s:tick(0.2, 0.1, player()), nil)
end)
test("invalid input and infinite aim are rejected", function()
    local s = ready()
    equal(s:input(1, true, {X=0/0,Y=0,Z=0}, 0), false)
    equal(s:input(1, true, {X=math.huge,Y=0,Z=0}, 0), false)
    equal(s:input(1, true, {X=0,Y=0,Z=0}, 0), false)
    equal(s:input(1.5, true, aim, 0), false)
    equal(s:input(1, 1, aim, 0), false)
end)
test("aim is normalized on the server", function()
    local s = ready(); assert(s:input(1, true, {X=3,Y=4,Z=0}, 0))
    near(s.aim.X, 0.6); near(s.aim.Y, 0.8)
end)
test("death or interruption requires release", function()
    local s = ready(); s:input(1, true, aim, 0)
    equal(s:tick(0, 0.1, {eligible=false,reason="dead"}), nil)
    equal(s.reason, "dead")
    equal(s:tick(0.1, 0.1, player()), nil)
end)
test("invalid stats fail closed", function()
    for _, value in ipairs({-1, 101, math.huge}) do
        local s = ready(); s:input(1, true, aim, 0)
        equal(s:tick(0, 0.1, player(value)), nil)
    end
end)
test("players have independent sessions", function()
    local a,b = ready(),ready(); a:input(1,true,aim,0)
    assert(a:tick(0,0.1,player())); equal(b:tick(0,0.1,player()),nil)
end)
test("respawn gets a fresh unheld session", function()
    local old = ready(); old:input(1,true,aim,0); assert(old:tick(0,0.1,player()))
    local new = ready(); equal(new:tick(0,0.1,player()),nil)
end)
test("config rejects NaN and excessive allocation", function()
    local c,w = Config.validate({ReliefSeconds=0/0,MaxStains=999999,StampsPerSecond=-1})
    equal(c.ReliefSeconds,8); equal(c.MaxStains,256); equal(c.StampsPerSecond,5); equal(#w,3)
end)
test("fade never exceeds lifetime", function()
    local c = Config.validate({StainSeconds=3,StainFadeSeconds=10})
    equal(c.StainFadeSeconds,3)
end)
test("keyboard follows hold and release", function()
    local i = Input.new()
    equal(i:update({keyboard=true},true).held,true)
    equal(i:update({},true).held,false)
end)
test("bumper tap queues one native hotbar action", function()
    local i = Input.new()
    equal(i:update({bumper=true},true).previousHotbar,false)
    equal(i:update({},true).previousHotbar,true)
    equal(i:update({},true).previousHotbar,false)
end)
test("chord never emits a drop or queued hotbar action", function()
    local i = Input.new(); i:update({bumper=true},true)
    local a = i:update({bumper=true,down=true},true)
    equal(a.held,true); equal(a.consumeDown,true); equal(a.drop,false)
    a = i:update({down=true},true)
    equal(a.held,false); equal(a.previousHotbar,false)
    equal(i:update({},true).previousHotbar,false)
end)
test("unmodified down drops normally", function()
    local i = Input.new()
    equal(i:update({down=true},true).drop,true)
    equal(i:update({down=true},true).drop,false)
end)
test("down before bumper is not the shortcut", function()
    local i = Input.new(); i:update({down=true},true)
    equal(i:update({down=true,bumper=true},true).held,false)
end)
test("menu interruption suppresses held input on return", function()
    local i = Input.new(); i:update({keyboard=true},true)
    equal(i:update({keyboard=true},false).held,false)
    equal(i:update({keyboard=true},true).held,false)
    i:update({},true)
    equal(i:update({keyboard=true},true).held,true)
end)
test("menu interruption cannot replay a queued hotbar tap", function()
    local i = Input.new(); i:update({bumper=true},true)
    i:update({bumper=true},false)
    equal(i:update({},true).previousHotbar,false)
end)
local hit = {kind="solid",position={X=0,Y=0,Z=0},normal={X=0,Y=0,Z=1}}
test("stains expire and fade at server timestamps", function()
    local e = Effects.new(Config.validate({})); local r = e:stamp("a",hit,0)
    equal(Effects.opacity(r,49),1); near(Effects.opacity(r,55),0.5)
    equal(Effects.opacity(r,60),0); equal(#e:snapshot(60),0)
end)
test("late join preserves remaining lifetime", function()
    local e = Effects.new(Config.validate({})); e:stamp("a",hit,0)
    equal(e:snapshot(40)[1].remaining,20)
end)
test("stamps are throttled independently for each player", function()
    local e = Effects.new(Config.validate({})); assert(e:stamp("a",hit,0))
    equal(e:stamp("a",hit,0.1),nil); assert(e:stamp("b",hit,0.1))
    assert(e:stamp("a",hit,0.2))
end)
test("oldest effects are evicted at the cap", function()
    local e = Effects.new(Config.validate({MaxStains=2}))
    e:stamp("a",hit,0);e:stamp("b",hit,0);e:stamp("c",hit,0)
    equal(#e.records,2);equal(e.records[1].id,2)
end)
test("water has cloud lifetime and never creates a solid stain", function()
    local e = Effects.new(Config.validate({}))
    local r = e:stamp("a",{kind="water",position=hit.position,normal=hit.normal},0)
    equal(r.kind,"water");equal(r.expires,4);equal(#e:snapshot(4),0)
end)
test("moving surface attachment data is preserved", function()
    local e = Effects.new(Config.validate({}))
    local r = e:stamp("a",{kind="solid",component="door",localPosition={X=1,Y=2,Z=3}},0)
    equal(r.component,"door");equal(r.localPosition.X,1)
end)
test("arc stops at the first obstruction", function()
    local calls = 0
    local r = Trajectory.trace({X=0,Y=0,Z=100},aim,400,function(a,b)
        calls = calls + 1
        if calls == 3 then return {kind="solid",position=b} end
    end)
    equal(calls,3);equal(r.hit.kind,"solid")
end)
test("arc falls under gravity and respects total travel range", function()
    local r = Trajectory.trace({X=0,Y=0,Z=100},aim,400,function() end)
    assert(r.endpoint.Z < 100)
    local length = 0
    for i=2,#r.points do
        local a,b=r.points[i-1],r.points[i]
        length=length+math.sqrt((a.X-b.X)^2+(a.Y-b.Y)^2+(a.Z-b.Z)^2)
    end
    near(length,400)
end)
test("first water hit prevents staining the submerged floor", function()
    local r = Trajectory.trace({X=0,Y=0,Z=100},aim,400,function(_,b)
        return {kind="water",position=b}
    end)
    equal(r.hit.kind,"water");equal(#r.points,2)
end)

for _, failure in ipairs(failures) do print("FAIL " .. failure) end
print(string.format("%d/%d tests passed", total - #failures, total))
assert(#failures == 0, "Gameplay tests failed")
return total
