local Config = require("pf.config")
local Session = require("pf.session")
local Input = require("pf.input")
local Effects = require("pf.effects")
local Trajectory = require("pf.trajectory")
local Pump = require("pf.pump")
local total, failures = 0, {}
local function equal(actual, expected)
    assert(actual == expected, tostring(actual) .. " ~= " .. tostring(expected))
end
local function near(actual, expected)
    assert(math.abs(actual - expected) < 0.00001, tostring(actual) .. " ~= " .. tostring(expected))
end
local function test(name, run)
    total = total + 1
    local ok, err = pcall(run)
    if not ok then failures[#failures + 1] = name .. ": " .. tostring(err) end
end
local function ready()
    local session = Session.new(Config.validate({}))
    assert(session:handshake("1.0.0", 1))
    return session
end
local aim = { X = 1, Y = 0, Z = 0 }
local function player(value) return { eligible = true, current = value or 0, maximum = 100 } end

test("eight seconds fully relieves existing need", function()
    local s, p = ready(), player()
    for i = 1, 80 do
        s:input(i, true, aim, i / 10)
        p.current = assert(s:tick(i / 10, 0.1, p))
    end
    near(p.current, 100); equal(s.active, false); equal(s.latched, true)
end)
test("partial release preserves partial relief", function()
    local s, p = ready(), player(40)
    s:input(1, true, aim, 0)
    near(s:tick(0, 0.1, p), 41.25)
    s:input(2, false, nil, 0.1)
    equal(s:tick(0.1, 0.1, p), nil); equal(s.active, false)
end)
test("full bladder relief requires a fresh release before restarting", function()
    local s = ready()
    s:input(1, true, aim, 0)
    near(s:tick(0, 0.1, player(99)), 100)
    s:input(2, true, aim, 0.1)
    equal(s:tick(0.1, 0.1, player(98)), nil)
    s:input(3, false, nil, 0.2)
    s:input(4, true, aim, 0.3)
    near(s:tick(0.3, 0.1, player(98)), 99.25)
end)
test("holding while empty cannot restart on natural need decay", function()
    local s = ready(); s:input(1, true, aim, 0)
    equal(s:tick(0, 0.1, player(100)), nil)
    equal(s:tick(0.1, 0.1, player(99)), nil)
end)
test("timeout stops at exactly one second", function()
    local s = ready(); s:input(1, true, aim, 0)
    assert(s:tick(0.1, 0.1, player()))
    equal(s:tick(1, 0.1, player()), nil); equal(s.reason, "input_timeout")
    s:input(2, true, aim, 1.1)
    equal(s:tick(1.1, 0.1, player()), nil)
end)
test("stalled frames cannot create bonus relief", function()
    local s = ready(); s:input(1, true, aim, 5)
    near(s:tick(5, 30, player()), 1.25)
end)
test("unready and incompatible sessions cannot modify stats", function()
    local s = Session.new(Config.validate({}))
    equal(s:input(1, true, aim, 0), false)
    equal(s:handshake("2.0.0", 1), false)
    equal(s:handshake("1.0.0", 2), false)
    equal(s:tick(0, 0.1, player()), nil)
end)
test("stale start packets cannot undo a release", function()
    local s = ready(); s:input(10, true, aim, 0); s:input(12, false, nil, 0.1)
    equal(s:input(11, true, aim, 0.2), false)
    equal(s:tick(0.2, 0.1, player()), nil)
end)
test("invalid input and infinite aim are rejected", function()
    local s = ready()
    equal(s:input(1, true, {X=0/0,Y=0,Z=0}, 0), false)
    equal(s:input(1, true, {X=math.huge,Y=0,Z=0}, 0), false)
    equal(s:input(1, true, {X=0,Y=0,Z=0}, 0), false)
    equal(s:input(1.5, true, aim, 0), false)
    equal(s:input(1, 1, aim, 0), false)
end)
test("aim is normalized on the server", function()
    local s = ready(); assert(s:input(1, true, {X=3,Y=4,Z=0}, 0))
    near(s.aim.X, 0.6); near(s.aim.Y, 0.8)
end)
test("death or interruption requires release", function()
    local s = ready(); s:input(1, true, aim, 0)
    equal(s:tick(0, 0.1, {eligible=false,reason="dead"}), nil)
    equal(s.reason, "dead")
    equal(s:tick(0.1, 0.1, player()), nil)
end)
test("invalid stats fail closed", function()
    for _, value in ipairs({-1, 101, math.huge}) do
        local s = ready(); s:input(1, true, aim, 0)
        equal(s:tick(0, 0.1, player(value)), nil)
    end
end)
test("players have independent sessions", function()
    local a,b = ready(),ready(); a:input(1,true,aim,0)
    assert(a:tick(0,0.1,player())); equal(b:tick(0,0.1,player()),nil)
end)
test("respawn gets a fresh unheld session", function()
    local old = ready(); old:input(1,true,aim,0); assert(old:tick(0,0.1,player()))
    local new = ready(); equal(new:tick(0,0.1,player()),nil)
end)
test("config rejects NaN and excessive allocation", function()
    local c,w = Config.validate({ReliefSeconds=0/0,MaxStains=999999,StampsPerSecond=-1})
    equal(c.ReliefSeconds,8); equal(c.MaxStains,256); equal(c.StampsPerSecond,5); equal(#w,3)
end)
test("fade never exceeds lifetime", function()
    local c = Config.validate({StainSeconds=3,StainFadeSeconds=10})
    equal(c.StainFadeSeconds,3)
end)
test("keyboard follows hold and release", function()
    local i = Input.new()
    equal(i:update({keyboard=true},true).held,true)
    equal(i:update({},true).held,false)
end)
test("bumper tap queues one native hotbar action", function()
    local i = Input.new()
    equal(i:update({bumper=true},true).previousHotbar,false)
    equal(i:update({},true).previousHotbar,true)
    equal(i:update({},true).previousHotbar,false)
end)
test("chord never emits a drop or queued hotbar action", function()
    local i = Input.new(); i:update({bumper=true},true)
    local a = i:update({bumper=true,down=true},true)
    equal(a.held,true); equal(a.consumeDown,true); equal(a.drop,false)
    a = i:update({down=true},true)
    equal(a.held,false); equal(a.previousHotbar,false)
    equal(i:update({},true).previousHotbar,false)
end)
test("unmodified down drops normally", function()
    local i = Input.new()
    equal(i:update({down=true},true).drop,true)
    equal(i:update({down=true},true).drop,false)
end)
test("down before bumper is not the shortcut", function()
    local i = Input.new(); i:update({down=true},true)
    equal(i:update({down=true,bumper=true},true).held,false)
end)
test("menu interruption suppresses held input on return", function()
    local i = Input.new(); i:update({keyboard=true},true)
    equal(i:update({keyboard=true},false).held,false)
    equal(i:update({keyboard=true},true).held,false)
    i:update({},true)
    equal(i:update({keyboard=true},true).held,true)
end)
test("menu interruption cannot replay a queued hotbar tap", function()
    local i = Input.new(); i:update({bumper=true},true)
    i:update({bumper=true},false)
    equal(i:update({},true).previousHotbar,false)
end)
local hit = {kind="solid",position={X=0,Y=0,Z=0},normal={X=0,Y=0,Z=1}}
test("stains expire and fade at server timestamps", function()
    local e = Effects.new(Config.validate({})); local r = e:stamp("a",hit,0)
    equal(Effects.opacity(r,49),1); near(Effects.opacity(r,55),0.5)
    equal(Effects.opacity(r,60),0); equal(#e:snapshot(60),0)
end)
test("late join preserves remaining lifetime", function()
    local e = Effects.new(Config.validate({})); e:stamp("a",hit,0)
    equal(e:snapshot(40)[1].remaining,20)
end)
test("stamps are throttled independently for each player", function()
    local e = Effects.new(Config.validate({})); assert(e:stamp("a",hit,0))
    equal(e:stamp("a",hit,0.1),nil); assert(e:stamp("b",hit,0.1))
    assert(e:stamp("a",hit,0.2))
end)
test("oldest effects are evicted at the cap", function()
    local e = Effects.new(Config.validate({MaxStains=2}))
    e:stamp("a",hit,0);e:stamp("b",hit,0);e:stamp("c",hit,0)
    equal(#e.records,2);equal(e.records[1].id,2)
end)
test("water has cloud lifetime and never creates a solid stain", function()
    local e = Effects.new(Config.validate({}))
    local r = e:stamp("a",{kind="water",position=hit.position,normal=hit.normal},0)
    equal(r.kind,"water");equal(r.expires,4);equal(#e:snapshot(4),0)
end)
test("moving surface attachment data is preserved", function()
    local e = Effects.new(Config.validate({}))
    local r = e:stamp("a",{kind="solid",component="door",localPosition={X=1,Y=2,Z=3}},0)
    equal(r.component,"door");equal(r.localPosition.X,1)
end)
test("arc stops at the first obstruction", function()
    local calls = 0
    local r = Trajectory.trace({X=0,Y=0,Z=100},aim,400,function(a,b)
        calls = calls + 1
        if calls == 3 then return {kind="solid",position=b} end
    end)
    equal(calls,3);equal(r.hit.kind,"solid")
end)
test("arc falls under gravity and respects total travel range", function()
    local r = Trajectory.trace({X=0,Y=0,Z=100},aim,400,function() end)
    assert(r.endpoint.Z < 100)
    local length = 0
    for i=2,#r.points do
        local a,b=r.points[i-1],r.points[i]
        length=length+math.sqrt((a.X-b.X)^2+(a.Y-b.Y)^2+(a.Z-b.Z)^2)
    end
    near(length,400)
end)
test("first water hit prevents staining the submerged floor", function()
    local r = Trajectory.trace({X=0,Y=0,Z=100},aim,400,function(_,b)
        return {kind="water",position=b}
    end)
    equal(r.hit.kind,"water");equal(#r.points,2)
end)

test("a hold begun inside a menu requires release after leaving it", function()
    local i = Input.new()
    equal(i:update({keyboard=true},false).held,false)
    equal(i:update({keyboard=true},true).held,false)
    i:update({},true)
    equal(i:update({keyboard=true},true).held,true)
end)

local Server = require("pf.server")
local function fixture()
    local game = {valid=function(o) return o and o.valid ~= false end,
        same=function(a,b) return a == b end,
        state=function(p) return p end,
        origin=function() return {X=0,Y=0,Z=100} end,
        applyRelief=function(p,value) p.current=value; p.writes=(p.writes or 0)+1 end}
    local net = {states={}, impacts={}, destroyed={}}
    function net:ownedBy(actor,p) return actor.owner == p end
    function net:destroy(actor) self.destroyed[actor]=true end
    function net:trace() return hit end
    function net:publishImpact(r) self.impacts[r.id]=r end
    function net:publishState(actor,s) self.states[actor]={active=s.active,reason=s.reason} end
    function net:stop(actor,reason) self.states[actor]={active=false,reason=reason} end
    function net:pruneImpacts(records)
        local alive={}
        for _,r in ipairs(records) do alive[r.id]=true end
        for id in pairs(self.impacts) do if not alive[id] then self.impacts[id]=nil end end
    end
    local s = Server.new(Config.validate({}),game,net)
    local p=player(); p.valid=true
    local actor={owner=p}
    s:add("one",p,actor)
    return s,p,actor,net,game
end
local function message(seq,held)
    return {mod="1.0.0",protocol=1,sequence=seq or 1,held=held ~= false,aim=aim}
end
test("server rejects packets addressed to another actor or owner",function()
    local s,p,a=fixture()
    equal(s:receive("one",{},message(),0),false)
    a.owner={}
    equal(s:receive("one",a,message(),0),false)
    s:tick(0,0.1); near(p.current,0)
end)
test("server rejects malformed envelopes without throwing",function()
    local s,p,a=fixture()
    equal(s:receive("one",a,nil,0),false)
    equal(s:receive("one",a,message(),0/0),false)
    equal(s:receive("missing",a,message(),0),false)
    s:tick(0,0.1); equal(p.writes,nil)
end)
test("server awards relief only after an owned compatible request",function()
    local s,p,a,n=fixture()
    s:tick(0,0.1); near(p.current,0)
    assert(s:receive("one",a,message(),0.1))
    s:tick(0.1,0.1); near(p.current,1.25); equal(n.states[a].active,true)
end)
test("duplicate simulation dispatch cannot award twice",function()
    local s,p,a=fixture(); s:receive("one",a,message(),0)
    s:tick(0,0.1); s:tick(0,0.1); near(p.current,1.25)
    s:tick(-1,0.1); near(p.current,1.25)
end)
test("failed native stat update stops effects and isolates other players",function()
    local s,p,a,n,g=fixture()
    local p2=player(); local a2={owner=p2}
    s:add("two",p2,a2)
    g.applyRelief=function(who,value)
        if who == p then error("binding changed") end
        who.current=value
    end
    s:receive("one",a,message(),0); s:receive("two",a2,message(),0)
    s:tick(0,0.1)
    equal(n.states[a].active,false); near(p2.current,1.25)
    equal(s.sessions.one.simulation.latched,true)
end)
test("disconnect destroys only that player's actor and releases session",function()
    local s,p,a,n=fixture(); s:receive("one",a,message(),0)
    s:tick(0,0.1); p.valid=false; s:tick(0.1,0.1)
    equal(s.sessions.one,nil); equal(n.destroyed[a],true)
    equal(s:receive("one",a,message(2),0.2),false)
end)
test("respawning rejects old actor packets",function()
    local s,p,a,n=fixture(); local replacement={owner=p}
    s:add("one",p,replacement)
    equal(n.destroyed[a],true)
    equal(s:receive("one",a,message(),0),false)
    s:tick(0,0.1); equal(p.writes,nil)
end)
test("world reset removes replicated cosmetics and sessions",function()
    local s,p,a,n=fixture(); s:receive("one",a,message(),0); s:tick(0,0.1)
    assert(next(n.impacts)); s:reset()
    equal(next(n.impacts),nil); equal(next(s.sessions),nil); equal(n.destroyed[a],true)
end)
test("version mismatch stops an already active player",function()
    local s,p,a,n=fixture(); s:receive("one",a,message(),0); s:tick(0,0.1)
    local wrong=message(2); wrong.mod="1.0.1"
    equal(s:receive("one",a,wrong,0.1),false); s:tick(0.1,0.1)
    near(p.current,1.25); equal(n.states[a].active,false)
end)

test("engine pump advances once at each simulation interval",function()
    local p=Pump.new(0.1)
    local due,diagnostic,dt=p:step(0,false)
    equal(due,true);equal(diagnostic,false);near(dt,0.1)
    equal(p:step(0.05,false),false)
    equal(p:step(0.1,false),true)
    equal(p:step(0.1,false),false)
end)
test("held diagnostic key emits once and rapid presses are bounded",function()
    local p=Pump.new(0.1)
    local _,shown=p:step(0,true);equal(shown,true)
    for i=1,50 do local _,again=p:step(i/10,true);equal(again,false) end
    p:step(5.1,false)
    local _,again=p:step(5.2,true);equal(again,true)
    p:step(5.3,false)
    local _,rapid=p:step(5.4,true);equal(rapid,false)
    p:step(6.3,false)
    local _,later=p:step(6.4,true);equal(later,true)
end)
test("pump clock reset and stalls cannot schedule catch-up bursts",function()
    local p=Pump.new(0.1)
    p:step(10,false)
    local due,_,dt=p:step(70,false);equal(due,true);near(dt,0.1)
    equal(p:step(70,false),false)
    local reset,_,resetDt=p:step(1,false);equal(reset,true);near(resetDt,0.1)
    equal(p:step(0/0,true),false)
end)

for _, failure in ipairs(failures) do print("FAIL " .. failure) end
print(string.format("%d/%d tests passed", total - #failures, total))
assert(#failures == 0, "Gameplay tests failed")
return total
